### ISSUE TITLE
Warning at \...SSViewer.php line 788: None of the following templates could be found (no theme in use): templates/StringTagField.ss 

### ISSUE THREAD

**Issue by barry-bookinglive** [silverstripe-labs/silverstripe-tagfield#30]
I get the following warning when trying to use the StringTagField...

Warning at \framework\view\SSViewer.php line 788: None of the following templates could be found (no theme in use): templates/StringTagField.ss

**Comment by 3Dgoo** [comment]
Yes, there is no StringTagField template. I've tried changing this to TagField.ss. This seems to fix that problem, although other problems pop up with StringTagField later on. 

Should StringTagField be calling _templates/TagField.ss_ instead of _templates/StringTagField.ss_ ? Or is there meant to be a _StringTagField.ss_ file?

**Comment by tractorcow** [comment]
@assertchris know if this is a quick fix?
